package modal;
// Generated Nov 12, 2023 4:00:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cartstatus generated by hbm2java
 */
@Entity
@Table(name="cartstatus"
    ,catalog="jsp_project"
)
public class Cartstatus  implements java.io.Serializable {


     private Integer id;
     private String descripton;
     private Set<Cart> carts = new HashSet<Cart>(0);

    public Cartstatus() {
    }

	
    public Cartstatus(String descripton) {
        this.descripton = descripton;
    }
    public Cartstatus(String descripton, Set<Cart> carts) {
       this.descripton = descripton;
       this.carts = carts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descripton", nullable=false, length=45)
    public String getDescripton() {
        return this.descripton;
    }
    
    public void setDescripton(String descripton) {
        this.descripton = descripton;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cartstatus")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


