package modal;
// Generated Oct 20, 2023 12:54:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="jsp_project"
)
public class Item  implements java.io.Serializable {


     private int id;
     private String name;
     private String imgurl;
     private Boolean isactive;

    public Item() {
    }

	
    public Item(int id) {
        this.id = id;
    }
    public Item(int id, String name, String imgurl, Boolean isactive) {
       this.id = id;
       this.name = name;
       this.imgurl = imgurl;
       this.isactive = isactive;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=225)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="imgurl", length=225)
    public String getImgurl() {
        return this.imgurl;
    }
    
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }




}


