package modal;
// Generated Nov 12, 2023 4:00:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="jsp_project"
)
public class Item  implements java.io.Serializable {


     private String id;
     private String name;
     private String imgurl;
     private Boolean isactive;
     private Integer sortkey;
     private Set<Cartitem> cartitems = new HashSet<Cartitem>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Item() {
    }

	
    public Item(String id) {
        this.id = id;
    }
    public Item(String id, String name, String imgurl, Boolean isactive, Integer sortkey, Set<Cartitem> cartitems, Set<Stock> stocks) {
       this.id = id;
       this.name = name;
       this.imgurl = imgurl;
       this.isactive = isactive;
       this.sortkey = sortkey;
       this.cartitems = cartitems;
       this.stocks = stocks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=20)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=225)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="imgurl", length=225)
    public String getImgurl() {
        return this.imgurl;
    }
    
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="sortkey")
    public Integer getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Integer sortkey) {
        this.sortkey = sortkey;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Cartitem> getCartitems() {
        return this.cartitems;
    }
    
    public void setCartitems(Set<Cartitem> cartitems) {
        this.cartitems = cartitems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


